apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudtest
  template:
    metadata:
      labels:
        app: cloudtest
    spec:
      containers:
      - name: nlp-app
        image: gcr.io/cloudcw-338918/myapp:v1
        ports:
        - containerPort: 3000
